// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-W2AkrdX_KRCxwlstSSyHF3P38hE9grY',
    appId: '1:252603448070:web:da07387621419825f1fc87',
    messagingSenderId: '252603448070',
    projectId: 'anilist-sort',
    authDomain: 'anilist-sort.firebaseapp.com',
    storageBucket: 'anilist-sort.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8xQf4UDuRGrBh_M1Umpqimtzb7Wxn1mc',
    appId: '1:252603448070:android:7840c5c66896e554f1fc87',
    messagingSenderId: '252603448070',
    projectId: 'anilist-sort',
    storageBucket: 'anilist-sort.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk45vJDCIlOIvzds9i0FpiZumZWbm_WHg',
    appId: '1:252603448070:ios:1cee814b82ea0115f1fc87',
    messagingSenderId: '252603448070',
    projectId: 'anilist-sort',
    storageBucket: 'anilist-sort.firebasestorage.app',
    iosBundleId: 'com.example.anilistFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk45vJDCIlOIvzds9i0FpiZumZWbm_WHg',
    appId: '1:252603448070:ios:1cee814b82ea0115f1fc87',
    messagingSenderId: '252603448070',
    projectId: 'anilist-sort',
    storageBucket: 'anilist-sort.firebasestorage.app',
    iosBundleId: 'com.example.anilistFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-W2AkrdX_KRCxwlstSSyHF3P38hE9grY',
    appId: '1:252603448070:web:aade466115667b5ff1fc87',
    messagingSenderId: '252603448070',
    projectId: 'anilist-sort',
    authDomain: 'anilist-sort.firebaseapp.com',
    storageBucket: 'anilist-sort.firebasestorage.app',
  );
}
